// <auto-generated />
namespace MenuDelDia.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class script_18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(script_18));
        
        string IMigrationMetadata.Id
        {
            get { return "201504142044204_script_18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
